# Model
model_name_or_path: swiss-ai/Apertus-8B-Instruct-2509
attn_implementation: flash_attention_2
dtype: bfloat16

# Dataset
dataset_name: ipst/slds
dataset_config: default
dataset_train_split: train
dataset_test_split: validation
dataset_num_proc: 32

# Hyperparameters
learning_rate: 2.0e-4
gradient_checkpointing: true
num_train_epochs: 3.0
logging_steps: 1
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
max_length: 4096
warmup_ratio: 0.03
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
output_dir: Apertus-FT/output/apertus_full
report_to: "wandb"
seed: 42

# Checkpointing:
save_strategy: steps
save_steps: 50
save_total_limit: 2
save_safetensors: true
resume_from_checkpoint: false
