# Model
model_name_or_path: swiss-ai/Apertus-70B-Instruct-2509
attn_implementation: flash_attention_2
dtype: bfloat16

# Dataset
dataset_name: ipst/slds
dataset_config: default
dataset_train_split: train
dataset_test_split: validation
dataset_num_proc: 32

# Hyperparameters
learning_rate: 2.0e-4
gradient_checkpointing: true
num_train_epochs: 4.0
logging_steps: 1

# BATCH SIZE STRATEGY
per_device_train_batch_size: 8
gradient_accumulation_steps: 4

# LoRA / PEFT
use_peft: true
lora_r: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules: all-linear

# Seq length & scheduler
max_seq_length: 8192

dataset_text_field: text

packing: false
warmup_ratio: 0.03
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1

# Checkpointing:
save_strategy: steps
save_steps: 50
save_total_limit: 2
save_safetensors: true
resume_from_checkpoint: true

# Output & logging
output_dir: Apertus-FT/output/apertus_70b_lora_r64_ctx8k
report_to: "wandb"
seed: 42
