compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 8
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_optimizer_pin_memory: true  # speeds up CPUâ†”GPU transfers
  offload_param_device: none  # keep params on GPU for speed
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
  # Add these for better CPU offload performance:
  overlap_comm: true
  contiguous_gradients: true
  sub_group_size: 1e9
  reduce_bucket_size: 5e8
  stage3_prefetch_bucket_size: 5e8
  stage3_param_persistence_threshold: 1e6
distributed_type: DEEPSPEED
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 12
num_processes: 48
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
